services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=true
      - PORT=3000
      - MONGODB_CONNECT=your_db_connection_string
      - JWT_SECRET=jwtscretetete
      - AWS_ACCESS_KEY=no_key_for_you
      - AWS_SECRET_ACCESS_KEY=never_has_been
    depends_on:
      - mongo

  mongo:
    image: mongo:7.0.14
    restart: always
    container_name: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: teco
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
